# Generated by Django 3.1.4 on 2021-01-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WB', 'Web Development'), ('DB', 'Desktop Development'), ('DS', 'Data Sience')], default='Web Development', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, default='Test@', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
